version: '3'

services:
  cbioportal:
    restart: unless-stopped
    image: ghcr.io/buschlab/cbioportal:${RELEASE:-latest}
    container_name: cbioportal_container
    environment:
      HTTP_PROXY: "http://${HTTPS_PROXY_HOST}:${HTTPS_PROXY_PORT}"
      NO_PROXY: "cbioportal,cbioportal_session"
    volumes:
     - ./study:/study/:z
     - ./config/application.properties:/cbioportal/application.properties:Z
     - ./config/security.properties:/cbioportal/security.properties:Z
     - ./config/frontend.json:/cbioportal/frontend.json:Z
     - ./config/${LOGO:-pm4onco.png}:/cbioportal-webapp/webapp/images/${LOGO:-pm4onco.png}:Z
     - ./config/cacerts:/etc/ssl/certs/java/cacerts:Z
     - cbioportal_portalinfo:/cbioportal/portalinfo:z
     - ./config/certs:/certs:z
    depends_on:
     - cbioportal_database
     - cbioportal-session
    networks:
     - cbioportal_net
    command: [
      "/usr/bin/java",
      "-Xms2g",
      "-Xmx4g",
      "-Doncokb.public_api.url=${ONCOKB_URL:-https://public.api.oncokb.org/api/v1}",
      "-Doncokb.token=${ONCOKB_TOKEN}",
      "-Dgenomenexus.url=/genome-nexus",
      "-Dsession.service.url=http://cbioportal-session:5000/api/sessions/my-portal/",
      "-Dshow.civic=${ENABLE_CIVIC:-true}",
      "-Dmycancergenome.show=${ENABLE_MYCANCERGENOME:-false}",
      "-Dquick_search.enabled=${ENABLE_QUICKSEARCH:-true}",
      "-Dfilter_groups_by_appname=false",
      "-Dhttps.proxyHost=${HTTPS_PROXY_HOST}",
      "-Dhttps.proxyPort=${HTTPS_PROXY_PORT}",
      "-Dfrontend.config=/cbioportal/frontend.json",
      "-Dskin.right_logo=${LOGO:-pm4onco.png}",
      "-Dspring.config.location=cbioportal/application.properties",
      "-Dauthenticate=${AUTHENTICATE:-false}",
      "-Dalways_show_study_group=${ALWAYS_SHOW_STUDY_GROUP:-none}",
      "-Dspring.security.oauth2.client.provider.keycloak.user-name-attribute=name",
      "-Dspring.security.oauth2.client.registration.keycloak.scope=openid,email,roles",
      "-Dspring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_REALM:-}",
      "-Dspring.security.oauth2.client.registration.keycloak.client-id=${KEYCLOAK_CLIENT_CBIOPORTAL:-}",
      "-Dspring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_SECRET_CBIOPORTAL:-}",
      "-Dsecurity.cors.allowed-origins=*",
      "-Dserver.tomcat.remoteip.port-header=X-Forwarded-Port",
      "-Dserver.tomcat.remoteip.protocol-header=X-Forwarded-Proto",
      "-cp",
      "/cbioportal-webapp:/cbioportal-webapp/lib/*",
      "org.cbioportal.PortalApplication"
    ]
  cbioportal_database:
    restart: unless-stopped
    image: docker.io/mariadb:11.2.2
    container_name: cbioportal_database_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-P@ssword1}
      MYSQL_DATABASE: cbioportal
      MYSQL_USER: cbio
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
    volumes:
     - ./data/cgds.sql:/docker-entrypoint-initdb.d/cgds.sql:Z
     - ./data/seed-cbioportal_hg19_hg38_v2.13.1.sql.gz:/docker-entrypoint-initdb.d/seed.sql.gz:Z
     - ./data/tableExtension.sql:/docker-entrypoint-initdb.d/tableExtension.sql:Z
     - cbioportal_data:/var/lib/mysql
    command:
     - --character-set-server=latin1
     - --collation-server=latin1_swedish_ci
     - --innodb_buffer_pool_size=${INNODB_BUFFER_POOL_SIZE:-100M}
    networks:
     - cbioportal_net
  cbioportal-session:
    restart: unless-stopped
    image: docker.io/cbioportal/session-service:0.6.1
    container_name: cbioportal_session_container
    environment:
      SERVER_PORT: 5000
      JAVA_OPTS: -Dspring.data.mongodb.uri=mongodb://cbioportal-session-database:27017/session-service
    depends_on:
      - cbioportal-session-database
    networks:
      - cbioportal_net
  cbioportal-session-database:
    restart: unless-stopped
    image: docker.io/mongo:4.2
    container_name: cbioportal_session_database_container
    environment:
      MONGO_INITDB_DATABASE: session_service
    volumes:
      - cbioportal_session_data:/data/db
    networks:
      - cbioportal_net
  fhirspark:
    restart: unless-stopped
    image: ghcr.io/buschlab/fhirspark:${RELEASE:-latest}
    container_name: cbioportal_fhirspark
    depends_on:
      - hapiserver
    environment:
      FHIRSPARK_FHIRBASE: http://hapiserver:8080/fhir
      FHIRSPARK_PORTALURL: http://cbioportal:8080/
      FHIRSPARK_LOGINREQUIRED: ${LOGINREQUIRED:-false}
    volumes:
      - ./data/drugs.json:/drugs.json:Z
      - ./data/hgnc.csv:/hgnc.csv:Z
    networks:
      - cbioportal_net
  hapiserver:
    restart: unless-stopped
    image: docker.io/hapiproject/hapi:v6.8.0
    container_name: cbioportal_fhirspark_hapiserver
    depends_on:
      - hapi-postgres
    environment:
      hapi.fhir.server_address: ${CBIOPORTAL_URL}/fhir
      hapi.fhir.local_base_url: http://hapiserver:8080/fhir
      hapi.fhir.reuse_cached_search_results_millis: 5000
      hapi.fhir.validation.requests_enabled: 'false'
      spring.datasource.url: "jdbc:postgresql://hapi-postgres:5432/hapi?currentSchema=public"
      spring.datasource.username: hapiserver
      spring.datasource.password: ${POSTGRES_USER_PASSWORD:-P@ssword2}
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
    networks:
      - cbioportal_net
  hapi-postgres:
    restart: unless-stopped
    image: docker.io/postgres:16.1-alpine
    container_name: cbioportal_fhirspark_database
    volumes:
      - fhir_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hapiserver
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD:-P@ssword2}
      POSTGRES_DB: hapi
    networks:
      - cbioportal_net
  cbioproxy:
    restart: unless-stopped
    image: ghcr.io/buschlab/cbioproxy:${RELEASE:-latest}
    container_name: cbioproxy_container
    volumes:
      - ./services/cbioproxy/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:Z
      - ./services/cbioproxy/cbioportal.conf:/etc/nginx/conf.d/cbioportal.conf:Z
      - ./services/cbioproxy/lua_auth_config.lua:/etc/nginx/conf.d/lua_auth_config.lua:Z
      - ./services/cbioproxy/lua_login_config.lua:/etc/nginx/conf.d/lua_login_config.lua:Z
      - ./services/cbioproxy/lua_resource_config.lua:/etc/nginx/conf.d/lua_resource_config.lua:Z
      - ./reports:/usr/share/reports:Z
      - ./config/attributes.json:/attributes.json:Z
      - ./data/tumorTypes.json:/tumorTypes.json:Z
      - ./config/keycloak.cer:/usr/local/share/ca-certificates/keycloak.cer:z
    environment:
      NGINX_LOGINREQUIRED: ${LOGINREQUIRED:-false}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-}
      KEYCLOAK_CLIENT_FHIRSPARK: ${KEYCLOAK_CLIENT_FHIRSPARK:-fhirspark}
      KEYCLOAK_SECRET_FHIRSPARK: ${KEYCLOAK_SECRET_FHIRSPARK:-nosecrethere}
      CBIOPORTAL_URL: ${CBIOPORTAL_URL:-//localhost:8080}
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - cbioportal
      - fhirspark
      - genomenexus
    networks:
      - cbioportal_net
  genomenexus:
    image: ghcr.io/buschlab/genome-nexus:${RELEASE:-latest}
    environment:
      - SERVER_PORT=8888
    restart: unless-stopped
    depends_on:
      - genomenexus_db
      - ensembl-rest
      - ensembl-mysql
    command: [
      "-Dhttps.proxyHost=${HTTPS_PROXY_HOST}",
      "-Dhttps.proxyPort=${HTTPS_PROXY_PORT}",
      "-Dspring.data.mongodb.uri=mongodb://genomenexus_db:27017/annotator",
      "-Dvep.url=http://ensembl-rest:3000/vep/human/hgvs/VARIANT?content-type=application/json&xref_refseq=1&ccds=1&canonical=1&domains=1&hgvs=1&numbers=1&protein=1",
      "-Dgenexrefs.url=http://ensembl-rest:3000/xrefs/id/ACCESSION?content-type=application/json",
      "-Densembl.sequence.url=http://localhost:3000/sequence/region/human/QUERY?content-type=application/json",
      "-DmutationAssessor.url=http://127.0.0.1/VARIANT&frm=json&fts=input,rgaa,rgvt,msa,pdb,F_impact,F_score,vc_score,vs_score,info,var,gene,uprot,rsprot,gaps,msa_height,chr,rs_pos,rs_res,up_pos,up_res,cnt_cosmic,cnt_snps",
      "-jar",
      "/app/genome-nexus.war"
    ]
    networks:
      - cbioportal_net
  genomenexus_db:
    image: docker.io/genomenexus/gn-mongo:0.31_mutationassessor
    volumes:
      - genomenexus_data:/bitnami/mongodb
    environment:
      - REF_ENSEMBL_VERSION=grch37_ensembl92
      - SPECIES=homo_sapiens
    restart: unless-stopped
    networks:
      - cbioportal_net
  ensembl-rest:
    image: docker.io/nr205/ensembl-rest:110
    restart: unless-stopped
    volumes:
      - ./config/ensembl_rest.conf:/opt/vep/src/ensembl-rest/ensembl_rest.conf:Z
    networks:
      - cbioportal_net
    depends_on:
      - ensembl-mysql
  ensembl-mysql:
    image: ghcr.io/buschlab/ensembl-mysql:latest
    restart: unless-stopped
    networks:
      - cbioportal_net

networks:
  cbioportal_net:

volumes:
  cbioportal_data:
  cbioportal_session_data:
  cbioportal_portalinfo:
  fhir_data:
  genomenexus_data:
