version: '3'

services:
  cbioportal:
    restart: unless-stopped
    image: docker.io/cbioportal/cbioportal:6.0.0
    container_name: cbioportal_container
    environment:
      HTTP_PROXY: "http://${HTTPS_PROXY_HOST}:${HTTPS_PROXY_PORT}"
      NO_PROXY: "cbioportal,cbioportal_session"
      DB_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
    volumes:
     - ./study:/study/:z
     - ./config/portal.properties:/cbioportal/application.properties:Z
     - ./config/client-tailored-saml-idp-metadata.xml:/cbioportal-webapp/WEB-INF/classes/client-tailored-saml-idp-metadata.xml:Z
     - ./config/samlKeystore.jks:/cbioportal-webapp/WEB-INF/classes/samlKeystore.jks:Z
     - ./config/${LOGO:-miracum.png}:/cbioportal-webapp/images/${LOGO:-pm4onco.png}:Z
     - cbioportal_portalinfo:/cbioportal/portalinfo:z
    depends_on:
     - cbioportal_database
     - cbioportal-session
    networks:
     - cbioportal_net
    command: [
      "java",
      "-Xms2g",
      "-Xmx4g",
      "-Doncokb.public_api.url=${ONCOKB_URL:-https://public.api.oncokb.org/api/v1}",
      "-Doncokb.token=${ONCOKB_TOKEN}",
      "-Dgenomenexus.url=/genome-nexus",
      "-Dsession.service.url=http://cbioportal-session:5000/api/sessions/my-portal/",
      "-Dshow.civic=${ENABLE_CIVIC:-true}",
      "-Dmycancergenome.show=${ENABLE_MYCANCERGENOME:-true}",
      "-Dquick_search.enabled=${ENABLE_QUICKSEARCH:-true}",
      "-Dfilter_groups_by_appname=false",
      "-Dsaml.sp.metadata.entityid=cbioportal",
      "-Dsaml.sp.metadata.entitybaseurl=${CBIOPORTAL_URL}",
      "-Dsaml.idp.metadata.location=classpath:/client-tailored-saml-idp-metadata.xml",
      "-Dsaml.idp.metadata.entityid=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}",
      "-Dsaml.keystore.location=classpath:/samlKeystore.jks",
      "-Dsaml.keystore.private-key.key=${KEYSTORE_KEY}",
      "-Dsaml.keystore.password=${KEYSTORE_PASSWORD}",
      "-Dsaml.keystore.default-key=${KEYSTORE_KEY}",
      "-Dsaml.keystore.private-key.password=${KEYSTORE_PASSWORD}",
      "-Dsaml.idp.metadata.attribute.email=email",
      "-Dsaml.idp.metadata.attribute.role=Role",
      "-Dsaml.custom.userservice.class=org.cbioportal.security.spring.authentication.keycloak.SAMLUserDetailsServiceImpl",
      "-Dhttps.proxyHost=${HTTPS_PROXY_HOST}",
      "-Dhttps.proxyPort=${HTTPS_PROXY_PORT}",
      "-Dskin.right_logo=${LOGO:-miracum.png}",
      "-cp",
      "/cbioportal-webapp:/cbioportal-webapp/lib/*",
      "org.cbioportal.PortalApplication",
      "--spring.config.location=cbioportal/application.properties",
      "--authenticate=${AUTHENTICATE:-false}"
    ]
  cbioportal_database:
    restart: unless-stopped
    image: docker.io/mariadb:11.2.2
    container_name: cbioportal_database_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-P@ssword1}
      MYSQL_DATABASE: cbioportal
      MYSQL_USER: cbio
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
    volumes:
     - ./data/cgds.sql:/docker-entrypoint-initdb.d/cgds.sql:Z
     - ./data/seed-cbioportal_hg19_hg38_v2.13.1.sql.gz:/docker-entrypoint-initdb.d/seed.sql.gz:Z
     - ./data/tableExtension.sql:/docker-entrypoint-initdb.d/tableExtension.sql:Z
     - cbioportal_data:/var/lib/mysql
    command:
     - --character-set-server=latin1
     - --collation-server=latin1_swedish_ci
     - --innodb_buffer_pool_size=${INNODB_BUFFER_POOL_SIZE:-100M}
    networks:
     - cbioportal_net
  cbioportal-session:
    restart: unless-stopped
    image: docker.io/cbioportal/session-service:0.6.1
    container_name: cbioportal_session_container
    environment:
      SERVER_PORT: 5000
      JAVA_OPTS: -Dspring.data.mongodb.uri=mongodb://cbioportal-session-database:27017/session-service
    depends_on:
      - cbioportal-session-database
    networks:
      - cbioportal_net
  cbioportal-session-database:
    restart: unless-stopped
    image: docker.io/mongo:4.2
    container_name: cbioportal_session_database_container
    environment:
      MONGO_INITDB_DATABASE: session_service
    volumes:
      - cbioportal_session_data:/data/db
    networks:
      - cbioportal_net
  cbioproxy:
    restart: unless-stopped
    image: ghcr.io/buschlab/cbioproxy:${RELEASE:-latest}
    environment:
      NGINX_LOGINREQUIRED: ${LOGINREQUIRED:-false}
    container_name: cbioproxy_container
    volumes:
      - ./services/cbioproxy/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:Z
      - ./services/cbioproxy/cbioportal-research.conf:/etc/nginx/conf.d/cbioportal.conf:Z
      - ./services/cbioproxy/lua_resource_config.lua:/etc/nginx/conf.d/lua_resource_config.lua:Z
      - ./reports:/usr/share/reports:Z
      - ./config/certs:/certs:z
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - cbioportal
      - genomenexus
    networks:
      - cbioportal_net
  genomenexus:
    image: ghcr.io/buschlab/genome-nexus:${RELEASE:-latest}
    environment:
      - SERVER_PORT=8888
    restart: unless-stopped
    depends_on:
      - genomenexus_db
      - ensembl-rest
      - ensembl-mysql
    command: [
      "-Dhttps.proxyHost=${HTTPS_PROXY_HOST}",
      "-Dhttps.proxyPort=${HTTPS_PROXY_PORT}",
      "-Dspring.data.mongodb.uri=mongodb://genomenexus_db:27017/annotator",
      "-Dvep.url=http://ensembl-rest:3000/vep/human/hgvs/VARIANT?content-type=application/json&xref_refseq=1&ccds=1&canonical=1&domains=1&hgvs=1&numbers=1&protein=1",
      "-Dgenexrefs.url=http://ensembl-rest:3000/xrefs/id/ACCESSION?content-type=application/json",
      "-Densembl.sequence.url=http://localhost:3000/sequence/region/human/QUERY?content-type=application/json",
      "-DmutationAssessor.url=http://127.0.0.1/VARIANT&frm=json&fts=input,rgaa,rgvt,msa,pdb,F_impact,F_score,vc_score,vs_score,info,var,gene,uprot,rsprot,gaps,msa_height,chr,rs_pos,rs_res,up_pos,up_res,cnt_cosmic,cnt_snps",
      "-jar",
      "/app/genome-nexus.war"
    ]
    networks:
      - cbioportal_net
  genomenexus_db:
    image: docker.io/genomenexus/gn-mongo:0.31_mutationassessor
    volumes:
      - genomenexus_data:/bitnami/mongodb
    environment:
      - REF_ENSEMBL_VERSION=grch37_ensembl92
      - SPECIES=homo_sapiens
    restart: unless-stopped
    networks:
      - cbioportal_net
  ensembl-rest:
    image: docker.io/nr205/ensembl-rest:110
    restart: unless-stopped
    volumes:
      - ./config/ensembl_rest.conf:/opt/vep/src/ensembl-rest/ensembl_rest.conf:Z
    networks:
      - cbioportal_net
    depends_on:
      - ensembl-mysql
  ensembl-mysql:
    image: ghcr.io/buschlab/ensembl-mysql:latest
    restart: unless-stopped
    networks:
      - cbioportal_net

networks:
  cbioportal_net:

volumes:
  cbioportal_data:
  cbioportal_session_data:
  cbioportal_portalinfo:
  genomenexus_data:
