version: '3'

services:
  cbioportal:
    restart: unless-stopped
    image: cbioportal/cbioportal:latest
    container_name: cbioportal_container
    environment:
      DB_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
    volumes:
     - ./study:/study/
     - ./config/portal.properties:/cbioportal/portal.properties:ro
    depends_on:
     - cbioportal_database
     - cbioportal_session
    networks:
     - cbioportal_net
    command: /bin/sh -c "java -Xms2g -Xmx4g -Ddb.password=${MYSQL_USER_PASSWORD:-P@ssword1} -Doncokb.public_api.url=https://www.oncokb.org/api/v1 -Doncokb.token=${ONCOKBTOKEN} -Dgenomenexus.url=/genome-nexus -Dauthenticate=${AUTHENTICATE:-noauthsessionservice} -Dsession.service.url=http://cbioportal_session:5000/api/sessions/my_portal/ -Dshow.civic=${ENABLE_CIVIC:-true} -Dmycancergenome.show=${ENABLE_MYCANCERGENOME:-true} -jar webapp-runner.jar -AmaxHttpHeaderSize=16384 -AconnectionTimeout=20000 --enable-compression /cbioportal-webapp"
  cbioportal_database:
    restart: unless-stopped
    image: mariadb:latest
    container_name: cbioportal_database_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-P@ssword1}
      MYSQL_DATABASE: cbioportal
      MYSQL_USER: cbio
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
    volumes:
     - ./data/cgds.sql:/docker-entrypoint-initdb.d/cgds.sql:ro
     - ./data/seed-cbioportal_hg19_v2.7.3.sql.gz:/docker-entrypoint-initdb.d/seed.sql.gz:ro
     - cbioportal_data:/var/lib/mysql
    command:
     - --character-set-server=latin1
     - --collation-server=latin1_swedish_ci
    networks:
     - cbioportal_net
  cbioportal_session:
    restart: unless-stopped
    image: cbioportal/session-service:latest
    container_name: cbioportal_session_container
    environment:
      SERVER_PORT: 5000
      JAVA_OPTS: -Dspring.data.mongodb.uri=mongodb://cbioportal_session_database:27017/session-service
    depends_on:
      - cbioportal_session_database
    networks:
      - cbioportal_net
  cbioportal_session_database:
    restart: unless-stopped
    image: mongo:3.7.9
    container_name: cbioportal_session_database_container
    environment:
      MONGO_INITDB_DATABASE: session_service
    volumes:
      - cbioportal_session_data:/data/db
    networks:
      - cbioportal_net
  nginx:
    restart: unless-stopped
    image: docker.miracum.org/cbioportal/cbioproxy:${RELEASE:-latest}
    container_name: cbioportal_nginx_container
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - cbioportal
      - genomenexus
    networks:
      - cbioportal_net
  genomenexus:
    image: docker.miracum.org/cbioportal/genome-nexus:${RELEASE:-latest}
    environment:
      - SERVER_PORT=8888
    restart: unless-stopped
    depends_on:
      - genomenexus_db
      - genomenexus_vep
    command: "-Dspring.data.mongodb.uri=mongodb://genomenexus_db:27017/annotator -Dgn_vep.region.url=http://genomenexus_vep:8080/vep/human/region/VARIANT -jar /app/genome-nexus.war"
    networks:
      - cbioportal_net
  genomenexus_db:
    image: docker.miracum.org/cbioportal/genome-nexus-db:${RELEASE:-latest}
    volumes:
      - genomenexus_data:/bitnami/mongodb
    environment:
      - REF_ENSEMBL_VERSION=grch37_ensembl92
      - SPECIES=homo_sapiens
    restart: unless-stopped
    networks:
      - cbioportal_net
  genomenexus_vep:
    image: docker.miracum.org/cbioportal/genome-nexus-vep:${RELEASE:-latest}
    environment:
      - VEP_ASSEMBLY=GRCh37
    restart: unless-stopped
    networks:
      - cbioportal_net

networks:
  cbioportal_net: 
  
volumes:
  cbioportal_data:
  cbioportal_session_data:
  genomenexus_data: