version: '3'

services:
  cbioportal:
    restart: unless-stopped
    image: docker.miracum.org/cbioportal/cbioportal:${RELEASE:-latest}
    build:
      context: services/cbioportal
    container_name: cbioportal_container
    environment:
      DB_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
    volumes:
     - ./study:/study/
     - ./config/portal.properties:/cbioportal/portal.properties:ro
     - ./config/frontend.json:/cbioportal/frontend.json:ro
    depends_on:
     - cbioportal_database
     - cbioportal_session
    ports:
      - "5005:5005"
      - "8081:8080"
    networks:
     - cbioportal_net
    command: /bin/sh -c "java -Xms2g -Xmx4g -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005 -Ddb.password=${MYSQL_USER_PASSWORD:-P@ssword1} -Doncokb.token=${ONCOKBTOKEN} -Dauthenticate=noauthsessionservice -Dsession.service.url=http://cbioportal_session:5000/api/sessions/my_portal/ -jar webapp-runner.jar /cbioportal-webapp"
  cbioportal_database:
    restart: unless-stopped
    image: mysql:5.7
    container_name: cbioportal_database_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-P@ssword1}
      MYSQL_DATABASE: cbioportal
      MYSQL_USER: cbio
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
    volumes:
     - ./data/cgds.sql:/docker-entrypoint-initdb.d/cgds.sql:ro
     - ./data/seed-cbioportal_hg19_v2.7.3.sql.gz:/docker-entrypoint-initdb.d/seed.sql.gz:ro
     - cbioportal_data:/var/lib/mysql 
    ports:
      - "3306:3306"
    networks:
     - cbioportal_net
  cbioportal_session:
    restart: unless-stopped
    image: cbioportal/session-service:latest
    container_name: cbioportal_session_container
    environment:
      SERVER_PORT: 5000
      JAVA_OPTS: -Dspring.data.mongodb.uri=mongodb://cbioportal_session_database:27017/session-service
    volumes:
      - cbioportal_data:/data/db
    depends_on:
      - cbioportal_session_database
    ports:
      - "5000:5000"
    networks:
      - cbioportal_net
  cbioportal_session_database:
    restart: unless-stopped
    image: mongo:3.7.9
    container_name: cbioportal_session_database_container
    environment:
      MONGO_INITDB_DATABASE: session_service
    ports:
      - "27017:27017"
    networks:
      - cbioportal_net
  fhirspark:
    restart: unless-stopped
    image: docker.miracum.org/cbioportal/fhirspark:${RELEASE:-latest}
    build:
      context: services/fhirspark
    container_name: cbioportal_fhirspark
    depends_on:
      - hapiserver
    environment:
      FHIRSPARK_FHIRBASE: http://hapiserver:8080/fhir/
      FHIRSPARK_SENDHL7V2: ${HL7V2ENABLE}
      FHIRSPARK_HL7V2SERVER: ${HL7V2SERVER}
      FHIRSPARK_HL7V2PORT: ${HL7V2PORT}
    ports:
      - "3001:3001"
    networks:
      - cbioportal_net
  hapiserver:
    restart: unless-stopped
    image: docker.miracum.org/miracum-data/hapi-fhir-jpaserver:8.0.1
    container_name: cbioportal_fhirspark_hapiserver
    volumes:
      - ./config/hapi.properties:/hapi-config/hapi.properties:ro
      - cbioportal_data:/var/lib/jetty/target
    ports:
      - "8082:8080"
    networks:
      - cbioportal_net
  nginx:
    restart: unless-stopped
    image: docker.miracum.org/cbioportal/cbioproxy:${RELEASE:-latest}
    build:
      context: services/cbioproxy
    container_name: cbioportal_nginx_container
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - cbioportal
    networks:
      - cbioportal_net

networks:
  cbioportal_net: 
  
volumes:
  cbioportal_data:
