version: '3'

services:
  cbioportal:
    restart: unless-stopped
    image: docker.miracum.org/cbioportal/cbioportal:${RELEASE:-latest}
    build:
      context: services/cbioportal
    container_name: cbioportal_container
    environment:
      DB_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
    volumes:
     - ./study:/study/
     - ./config/portal.properties:/cbioportal/portal.properties:ro
    depends_on:
     - cbioportal_database
     - cbioportal_session
    ports:
      - "5005:5005"
      - "8081:8080"
    networks:
     - cbioportal_net
    command: /bin/sh -c "java -Xmx4g -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005 -Ddb.password=${MYSQL_USER_PASSWORD:-P@ssword1} -Doncokb.token=${ONCOKBTOKEN} -Dauthenticate=noauthsessionservice -Dsession.service.url=http://cbioportal_session:5000/api/sessions/my_portal/ -jar webapp-runner.jar /cbioportal-webapp"
  cbioportal_database:
    restart: unless-stopped
    image: mariadb:latest
    container_name: cbioportal_database_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-P@ssword1}
      MYSQL_DATABASE: cbioportal
      MYSQL_USER: cbio
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
    volumes:
     - ./data/cgds.sql:/docker-entrypoint-initdb.d/cgds.sql:ro
     - ./data/seed-cbioportal_hg19_v2.7.3.sql.gz:/docker-entrypoint-initdb.d/seed.sql.gz:ro
     - cbioportal_data:/var/lib/mysql
    command:
     - --character-set-server=latin1
     - --collation-server=latin1_swedish_ci
    ports:
      - "3306:3306"
    networks:
     - cbioportal_net
  cbioportal_session:
    restart: unless-stopped
    image: cbioportal/session-service:latest
    container_name: cbioportal_session_container
    environment:
      SERVER_PORT: 5000
      JAVA_OPTS: -Dspring.data.mongodb.uri=mongodb://cbioportal_session_database:27017/session-service
    volumes:
      - cbioportal_data:/data/db
    depends_on:
      - cbioportal_session_database
    ports:
      - "5000:5000"
    networks:
      - cbioportal_net
  cbioportal_session_database:
    restart: unless-stopped
    image: mongo:3.7.9
    container_name: cbioportal_session_database_container
    environment:
      MONGO_INITDB_DATABASE: session_service
    ports:
      - "27017:27017"
    networks:
      - cbioportal_net
  fhirspark:
    restart: unless-stopped
    image: docker.miracum.org/cbioportal/fhirspark:${RELEASE:-latest}
    build:
      context: services/fhirspark
    container_name: cbioportal_fhirspark
    depends_on:
      - hapiserver
    environment:
      FHIRSPARK_FHIRBASE: http://hapiserver:8080/fhir/
      FHIRSPARK_SENDHL7V2: ${HL7V2ENABLE:-false}
      FHIRSPARK_HL7V2SERVER: ${HL7V2SERVER}
      FHIRSPARK_HL7V2PORT: ${HL7V2PORT}
    volumes:
      - ./data/drugs.json:/drugs.json:ro
      - ./data/hgnc.csv:/hgnc.csv:ro
    ports:
      - "3001:3001"
    networks:
      - cbioportal_net
  hapiserver:
    restart: unless-stopped
    image: docker.miracum.org/miracum-data/hapi-fhir-jpaserver:v8.1.1
    container_name: cbioportal_fhirspark_hapiserver
    ports:
      - "8082:8080"
    depends_on:
      - hapi-postgres
    environment:
      server.address: "http://hapiserver:8080/fhir/"
      reuse_cached_search_results_millis: 5000
      datasource.url: "jdbc:postgresql://hapi-postgres:5432/hapi?currentSchema=public"
      datasource.username: hapiserver
      datasource.password: ${POSTGRES_USER_PASSWORD:-P@ssword2}
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      datasource.driver: org.postgresql.Driver
      validation.requests.enabled: "false"
    networks:
      - cbioportal_net
  hapi-postgres:
    restart: unless-stopped
    image: postgres:12.3-alpine
    container_name: cbioportal_fhirspark_database
    volumes:
      - fhir_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: hapiserver
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD:-P@ssword2}
      POSTGRES_DB: hapi
    ports:
      - "5432:5432"
    networks:
      - cbioportal_net
  nginx:
    restart: unless-stopped
    image: docker.miracum.org/cbioportal/cbioproxy:${RELEASE:-latest}
    build:
      context: services/cbioproxy
    container_name: cbioportal_nginx_container
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - cbioportal
      - fhirspark
    networks:
      - cbioportal_net

networks:
  cbioportal_net: 
  
volumes:
  cbioportal_data:
  fhir_data:
