version: '3'

services:
  cbioportal:
    image: ghcr.io/buschlab/cbioportal:${RELEASE:-latest}
    container_name: cbioportal_init
    user: root
    environment:
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD:-P@ssword1}
    volumes:
     - ./data:/data/:z
     - ./config/:/config/:z
     - ./init.sh:/init.sh:z
    command: /bin/sh -c "cd / && /init.sh"
    entrypoint: []
