services:
  mtbimporter:
    restart: unless-stopped
    image: ghcr.io/pm4onco/mtbimporter:latest
    command: "/app/settings.yaml"
    volumes:
      - "/run/user/1000/podman/podman.sock:/var/run/docker.sock:z"
      - "./settings.yaml:/app/settings.yaml:z"
      - "./input:/app/input:z"
      - "./mapper:/mapper:z"
      - "./processed:/app/processed:z"
      - "../../study:/home/nreimer/git/MTB-cbioportal/study:z"
      - "./template:/app/template:z"
      - "../../reports:/app/reports:z"
    networks:
      - mtb-cbioportal_cbioportal_net
    entrypoint: [
      "java",
      "-Xmx8g",
      "-jar",
      "/app/mtbimporter.jar"
    ]
networks:
  mtb-cbioportal_cbioportal_net:
    external: true
