name: Docker build (research)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build containers
        run: docker-compose --f docker-compose-research.yml build
