name: Docker build (mtb)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Build mtb cBioPortal
        run: FLAVOR=mtb docker compose build cbioportal
      - name: Build mtb cbioproxy
        run: FLAVOR=mtb docker compose build cbioproxy
