name: Release genome-nexus

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: gnome-nexus Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/pm4onco/genome-nexus
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: genome-nexus Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./services/genome-nexus
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
