name: Docker build (research)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Build research containers
        run: docker-compose -f compose-research.yml build cbioportal
      - name: Build research cbioproxy
        run: docker-compose -f compose-research.yml build cbioproxy
