name: Docker build (research)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Build research containers
        run: docker-compose -f docker-compose-research.yml build cbioportal
      - name: Build research cbioproxy
        run: docker-compose -f docker-compose-research.yml build cbioproxy
