name: Docker build (dev)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build dev containers
        run: docker-compose -f docker-compose-dev.yml build cbioportal
      - name: Build dev cbioproxy
        run: docker-compose -f docker-compose-dev.yml build nginx
