name: Docker build (dev)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Build dev containers
        run: docker-compose -f compose-dev.yml build cbioportal
      - name: Build dev cbioproxy
        run: docker-compose -f compose-dev.yml build cbioproxy
      - name: Login to Docker registry
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push cbioportal
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: docker-compose -f compose-dev.yml push cbioportal
      - name: Push cbioproxy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: docker-compose -f compose-dev.yml push cbioproxy
