name: Docker build (care)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Build care cBioPortal
        run: FLAVOR=care docker compose build cbioportal
      - name: Build care cbioproxy
        run: FLAVOR=care docker compose build cbioproxy
