name: Docker build (research)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Build research containers
        run: docker compose -f compose-research.yml build cbioportal
      - name: Build research cbioproxy
        run: docker compose -f compose-research.yml build cbioproxy
