name: Docker build (research)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Build research containers
        run: FLAVOR=research docker compose build cbioportal
      - name: Build research cbioproxy
        run: FLAVOR=research docker compose build cbioproxy
