name: Docker build (care)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Build care cBioPortal
        run: docker compose -f compose.yml build cbioportal
      - name: Build care cbioproxy
        run: docker compose -f compose.yml build cbioproxy
