name: Docker build (dev)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Build dev containers
        run: docker compose -f compose-dev.yml build cbioportal
      - name: Build dev cbioproxy
        run: docker compose -f compose-dev.yml build cbioproxy
      - name: Login to Docker registry
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push cbioportal
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: docker compose -f compose-dev.yml build cbioportal --push
      - name: Push cbioproxy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: docker compose -f compose-dev.yml build cbioproxy --push
