name: Docker build (research)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build research containers
        run: docker-compose -f docker-compose-research.yml build cbioportal
      - name: Build research cbioproxy
        run: docker-compose -f docker-compose-research.yml build cbioproxy
