name: Docker build (care)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build care containers
        run: docker-compose --f docker-compose.yml build
